# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "grooveshark-ruby"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabriel Scholz"]
  s.date = "2012-10-12"
  s.description = "An easy-to-use ruby wrapper for the Grooveshark API"
  s.email = "scholz.gabe@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "grooveshark-ruby.gemspec",
    "lib/grooveshark-ruby.rb",
    "lib/grooveshark-ruby/autocomplete.rb",
    "lib/grooveshark-ruby/autoplay.rb",
    "lib/grooveshark-ruby/core.rb",
    "lib/grooveshark-ruby/new.rb",
    "lib/grooveshark-ruby/recs.rb",
    "lib/grooveshark-ruby/register.rb",
    "lib/grooveshark-ruby/request.rb",
    "lib/grooveshark-ruby/search.rb",
    "lib/grooveshark-ruby/sessions.rb",
    "lib/grooveshark-ruby/subscriberstreams.rb",
    "lib/grooveshark-ruby/tinysong.rb",
    "lib/grooveshark-ruby/trials.rb",
    "lib/grooveshark-ruby/urls.rb",
    "lib/grooveshark-ruby/users.rb"
  ]
  s.homepage = "http://github.com/garbles/grooveshark-ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "An easy-to-use ruby wrapper for the Grooveshark API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

